### ISSUE TITLE
Major things that still need to get done for the vanilla ROSplane

### ISSUE THREAD

**Issue by gellings** [BYU-MAGICC/ros_plane#14]
- [x] Add feed forward to the roll loop
- [x] Fix takeoff acceleration bug
- [x] return to home
- [x] Waypoint handling
- [x] publish latitude and longitude with state

Anything else?

**Comment by superjax** [comment]
What about simulator support?  Do we need the simulator to be a in a specific state in order for a release of ros_plane?

**Comment by superjax** [comment]
If we do want sim support, here is that release issue #fcu_sim/45

**Comment by plusk01** [comment]
We need to determine how to drive a GPS sensor.

**Comment by gellings** [comment]
We've made some good progress!  The sim stuff is coming along.  It would be nice to be able to do rosflight SIL. I haven't been able to make it work because of a calibration bug.   We still lack some work on waypoint handling and integrating with the ground station.

**Comment by gellings** [comment]
The readme also needs to be rewritten now that the simulation location has changed and we have multiple packages.
