### ISSUE TITLE
chase cam dependencies on fcu_sim

### ISSUE THREAD

**Issue by gellings** [BYU-MAGICC/ros_plane#47]
The fixedwing xacro has a commented gimble and chase came from fcu_sim.  At least the chase came would be nice to include.  Any ideas if that belongs in rosflight_plugins?  Any thoughts?

**Comment by plusk01** [comment]
This would belong in the `magicc_sim` repo (the thought being that it isn't part of the minimal, general functionality).

https://github.com/byu-magicc/magicc_sim

**Comment by skyler237** [comment]
Agreed. On that same note, will fcu_sim still exist, or is anything left being migrated to magicc_sim?

**Comment by plusk01** [comment]
@skyler237 fcu_sim is deprecated and should no longer be used.
