### ISSUE TITLE
Inaccurate state estimation

### ISSUE THREAD

**Issue by drinkdhmo** [BYU-MAGICC/ros_plane#8]
It appears that the state estimation is wildly inaccurate. Attempting to feed the autopilot the estimated state results in failure to fly. Is this an issue with the master branch? Is it fixed in RC1.0?

**Comment by gellings** [comment]
@drinkdhmo RC1.0 should be flying on estimates as of now.  It doesn't fly great initially but it seems to converge fine.  I think the problem my have been with the GPS plugin, I fixed several bugs today.
